# Generated by Django 3.2.2 on 2021-05-14 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacao', '0001_initial'),
        ('agente', '0001_initial'),
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='id',
        ),
        migrations.AddField(
            model_name='transacao',
            name='agente',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agente.agente'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='operacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='operacao.operacao'),
        ),
    ]
