# Generated by Django 3.2.3 on 2021-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
            ],
        ),
    ]
