# Generated by Django 3.2.2 on 2021-05-14 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saldo', '0001_initial'),
        ('gasto', '0001_initial'),
        ('divida', '0001_initial'),
        ('banco', '0001_initial'),
        ('ganho', '0001_initial'),
        ('transacao', '0002_auto_20210514_0335'),
        ('poupanca', '0001_initial'),
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='agent_fin',
            field=models.ManyToManyField(to='banco.Banco'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='divida',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='divida.divida'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='ganho',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ganho.ganho'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='gasto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gasto.gasto'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='poupanca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='poupanca.poupanca'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='saldo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='saldo.saldo'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='transacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='transacao.transacao'),
        ),
    ]
