# Generated by Django 3.2.2 on 2021-05-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carteira',
            field=models.ManyToManyField(to='carteira.Carteira'),
        ),
    ]
