# Generated by Django 3.2.2 on 2021-05-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('datah_ini', models.DateTimeField()),
                ('datah_fim', models.DateTimeField()),
                ('datah_ag', models.DateTimeField()),
            ],
        ),
    ]
